### ISSUE TITLE
No releases

### ISSUE THREAD

**Issue by Otakubuns** [Bacon1661/wizard101-rpc#1]
Hello, first off I'm super happy someone has made this since the one from 2 years ago doesn't work anymore so ty! 
But there aren't any releases actually in the releases section. Just wondering when that's gonna be out because in the readme the link to releases is there.

**Comment by Bacon1661** [comment]
I never made a release because I wasn't satisfied with the final result, as well as there being no apparent interest in the project until now. Expecting users to use a cli was a bad idea from the get-go, so I'm currently working on a gui in the [electron](https://github.com/Bacon1661/Wizard101-RPC/tree/electron) branch. 

If you'd like to use the console version it should be easy enough. Just install the latest version of node.js, download the contents of the master branch, and run `node .` in the project's directory.

**Comment by Otakubuns** [comment]
oh alright, thank you! I'm not well versed in node.js so I wasn't exactly sure how to do it.
I look forward to using the gui version!
